"""
The range() function in Python generates a sequence of numbers. 
It is commonly used in for loops to iterate over a sequence of numbers.

Parameters:
    - stop: The stop parameter defines the end of the sequence. 
        The sequence generated by range() will not include this value.
    
    - start (optional): The start parameter defines the start of the sequence. 
        If specified, the sequence will start from this value. If not specified, it defaults to 0.
        
    - step (optional): The step parameter defines the increment (or decrement) between each number in the sequence. 
        If specified, the sequence will be generated with this step. If not specified, it defaults to 1.
Usage:
    - range(stop): 
        Generates a sequence of numbers from 0 up to (but not including) the stop value. 
        The start parameter defaults to 0, and the step parameter defaults to 1.

    - range(start, stop):
        Generates a sequence of numbers from start up to (but not including) the stop value.

    - range(start, stop, step): 
        Generates a sequence of numbers starting from the start value, 
        up to (but not including) the stop value, incrementing by the step value.

    If the start and step parameters are not specified, they default to 0 and 1 respectively.

    # Example usage:
        def printLine():
            print("----------------------------")

        # Usage with only stop parameter (start defaults to 0, step defaults to 1)
        for i in range(5):
            print(i)
        printLine()

        # Usage with specified start and specified stop (start defaults to 0, step defaults to 1)
        for j in range(2,6):
            print(j)
        printLine()

        # Usage with specified start, stop, and step parameters
        for k in range(1, 8, 2):
            print(k)
        printLine()

        # Usage with a negative step to generate a decreasing sequence
        for l in range(6, 0, -1):
            print(l)
        printLine()
"""
def printLine():
    print("----------------------------")

# Usage with only stop parameter (start defaults to 0, step defaults to 1)
for i in range(5):
    print(i)
printLine()

# Usage with specified start and specified stop (start defaults to 0, step defaults to 1)
for j in range(2,6):
    print(j)
printLine()

# Usage with specified start, stop, and step parameters
for k in range(1, 8, 2):
    print(k)
printLine()

# Usage with a negative step to generate a decreasing sequence
for l in range(6, 0, -1):
    print(l)
printLine()